import { createSlice } from "@reduxjs/toolkit";
import { initialState, sliceName } from "./constants";

export const appSlice = createSlice({
  name: sliceName,
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setIsSidebarOpen: (state, action) => {
      state.isSideBarOpen = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const { setIsSidebarOpen } = appSlice.actions;

export default appSlice.reducer;
